semantic-rs/semantic-rs

- Cargo.toml
> Add author

- src/main.rs
- src/toml_file.rs
Fix compiler warnings in several modules
> Fix warnings

- src/main.rs
- src/toml_file.rs
This fixes the issue that the path the user specified wasn't taken into
account when reading the Cargo.toml file
> fix(toml_file): Pass path to toml_file

- Cargo.lock
- Cargo.toml
- src/git.rs
- src/main.rs
When `Cargo.toml` was updated with the new version it is now committed back in the repository.
> Commit updated cargo file

- Cargo.lock
- Cargo.toml
- src/changelog.rs
- src/git.rs
- src/main.rs
I though this needs #28 first, but it just pulled in the same commits.
Merging #28 first, then this should be fine as well.
> Write changelog with new version

- src/changelog.rs
- src/logger.rs
- src/main.rs
This PR removes warnings b/c of unused code and imports
> Reduce warnings

- Cargo.lock
- Cargo.toml
- src/git.rs
- src/main.rs
This PR integrates all functionality from https://github.com/badboy/git2-commit-rs in the git module.
> Integrate git2_commit crate

- src/main.rs
> fix: Better error when repository path was not found

- README.md
This Pull Request improves the information for the end user:
- Better explanation of the workflow and the steps semantic-rs performs
Missing:
- Installation instructions
> docs: Improve explanation for end users

- Cargo.lock
- Cargo.toml
- src/git.rs
- src/main.rs
> fix: Canonicalize path to absolute path

- .travis.yml
- Cargo.lock
Extracted from #62 to make the other PR smaller.
> Upgrade deps

- .travis.yml
- Cargo.lock
- Cargo.toml
- src/cargo.rs
- src/config.rs
- src/error.rs
- src/git.rs
- src/github.rs
- src/main.rs
- tests/integration/integration.bats
This is a first shot at #15 and #16
> GitHub release

- src/config.rs
- src/git.rs
- src/main.rs
- src/toml_file.rs
Just some stylistic nits, but perhaps it'll be useful. Cheers!
> fixed some clippy warnings

- README.md
This documents the recent changes made to the behavior and user interface.
> docs: Update README with the latest changes

- .travis.yml
This enables Homu. Queue at http://homu.hellorust.com/queue/semantic-rs/semantic-rs
> chore: Enable homu

- README.md
This adds information about which test project to use to have the best development experience.
> docs: Update development section

- tests/integration/run-locally.sh
> fix: Avoid non-POSIX readlink parameter

- README.md
assuming the intention is linking to crates.io website
> doc: fix broken link

- README.md
Add missing test documentation
Closes #102
> docs: document test usage

- src/config.rs
- src/main.rs
- src/preflight.rs
Belongs to #92 
This adds a preflight module which performs checks to see if the user has configured everything for a successful run such as:
- CARGO_TOKEN
- GH_TOKEN
- repository has `origin` remote
> Better user information

- .travis.yml
let's see if this works out of the box
> switch to xenial
